export const en: any = {
    0: "aidchat",
    1: 'Why',
    2: "Report a worker",
    3: 'Because a brain never rests, so it needs some extra care.',
    4: 'How it works?',
    5: 'Back to Home',
    6: 'Login',
    7: 'Register',
    8: `Haven't contributed yet? Sign up`,
    9: 'Name',
    10: 'Email',
    11: 'Password',
    12: 'Contact',
    13: 'Already contributing? Sign In',
    14: 'Enter OTP sent to contact',
    15: 'Back to register',
    16: 'Forgot password?',
    17: 'Back to login',
    18: 'MY REPORTS',
    19: 'MY EARNING',
    20: 'MY SUBMISSIONS',
    21: 'SUBMISSION VIEWED',
    22: 'Logout'
}

export enum enString {
    app_name,
    why,
    report_worker,
    auth_banner_text,
    btnHowitWork,
    backToSearch,
    login,
    register,
    notcontributedyet,
    name,
    email,
    password,
    contact,
    alreadyContributing,
    enterOTP,
    backToRegister,
    forgetPassword,
    backToLogin,
    myreport,
    myearning,
    mysubmission,
    submissionviewed,
    logout
}